config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  root 'home#index'
  resources :bank_accounts, only: :destroy do
    patch '/reactivate', to: 'bank_accounts#reactivate'
    get '/balance', to: 'bank_accounts#balance', on: :collection
    get '/statement', to: 'bank_accounts#statement', on: :collection
  end
  resources :deposits, only: %i[new create]
  resources :withdraws, only: %i[new create]
  resources :transfers, only: %i[new create]
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
  before_action :authenticate_client!

  def new
    @withdraw = Debit.new
  end

  def create
    @withdraw = Debit.new(debit_type: 'withdraw', amount: amount, bank_account: current_client.bank_account)
    if @withdraw.save
      flash[:success] = 'Saque realizado com sucesso.'
      redirect_to new_withdraw_path
    else
      @withdraw.amount = ''
      flash.now[:error] = 'Não foi possível realizar o saque.'
      render 'new'
    end
  end

  private

  def debit_params
    params.require(:debit).permit(:amount)
  end

  def amount
    IntegerToCentsConverter.call(debit_params[:amount])
  end
end

app/views/withdraws/new.html.erb
<section class="d-flex flex-column">
  <div class="d-flex m-auto shadow-lg p-5 flex-column">
    <h2 class="mb-3">Saque</h2>
    <p>Seu saldo: <%= number_to_currency(current_client.try(:bank_account).try(:real_balance)) %></p>

    <%= form_with model: @withdraw, url: withdraws_path do |f| %>
      <%= render 'error_messages', resource: @withdraw %>

      <%= render 'amount_field', f: f %>

      <div class="actions">
        <%= f.submit 'Sacar', class: 'w-100 btn btn-lg btn-primary fw-bolder mt-2' %>
      </div>
    <% end %>

    <div class="links d-flex justify-content-center flex-column mt-2">
      <%= link_to 'Voltar', root_path, class:'text-primary text-decoration-none fw-bolder' %>
    </div>
  </div>
</section>