config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  root 'home#index'
  resources :bank_accounts, only: :destroy do
    patch '/reactivate', to: 'bank_accounts#reactivate'
    get '/balance', to: 'bank_accounts#balance', on: :collection
    get '/statement', to: 'bank_accounts#statement', on: :collection
  end
  resources :deposits, only: %i[new create]
  resources :withdraws, only: %i[new create]
  resources :transfers, only: %i[new create]
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_client!
  before_action :check_payee, :check_transfer, only: :create

  def new
    @transfer = Debit.new
  end

  def create
    if BankTransferFeeMaker.call(@transfer)
      Credit.create!(credit_type: 'transfer', amount: @transfer.amount, bank_account: payee.bank_account)
      flash[:success] = 'Transferência realizada com sucesso.'
      redirect_to new_transfer_path
    else
      @transfer.errors.add(:bank_account, :insufficient_balance)
      @transfer.amount = ''
      flash.now[:error] = 'Não foi possível realizar a transferência.'
      render 'new'
    end
  end

  private

  def transfer_params
    params.require(:debit).permit(:payees_registration_number, :amount)
  end

  def payee
    payees_registration_number = transfer_params[:payees_registration_number]

    return unless current_client&.registration_number != payees_registration_number

    Client.find_by(registration_number: payees_registration_number)
  end

  def amount
    IntegerToCentsConverter.call(transfer_params[:amount])
  end

  def check_payee
    return if payee&.bank_account&.active?

    @transfer = Debit.new
    @transfer.errors.add(:client, 'não encontrado ou conta bancária encerrada')
    flash.now[:error] = 'Não foi possível realizar a transferência.'
    render 'new'
  end

  def check_transfer
    @transfer = Debit.new(debit_type: 'transfer', amount: amount, bank_account: current_client.bank_account)

    return if @transfer.valid?

    @transfer.amount = ''
    flash.now[:error] = 'Não foi possível realizar a transferência.'
    render 'new'
  end
end

app/views/transfers/new.html.erb
<section class="d-flex flex-column">
  <div class="d-flex m-auto shadow-lg p-5 flex-column">
    <h2 class="mb-3">Transferência entre contas</h2>
    <p>Seu saldo: <%= number_to_currency(current_client.try(:bank_account).try(:real_balance)) %></p>

    <%= form_with model: @transfer, url: transfers_path, method: :post do |f| %>
      <%= render 'error_messages', resource: @transfer %>

      <div class="field form-floating">
        <%= f.text_field :payees_registration_number, autofocus: true, autocomplete: 'payees_registration_number', class: 'form-control', placeholder: ' ', required: true %>
        <%= f.label :payees_registration_number, 'CPF do favorecido' %><br />
      </div>

      <%= render 'amount_field', f: f %>

      <div class="actions">
        <%= f.submit 'Transferir', class: 'w-100 btn btn-lg btn-primary fw-bolder mt-2' %>
      </div>
    <% end %>

    <div class="alert alert-info mt-4">
      <dl>
        <dt>Taxa de transferência:</dt>
        <dd>R$ 5,00 de segunda a sexta das 9 às 18 horas</dd>
        <dd>R$ 7,00 nos demais horários</dd>
        <dd>R$ 10,00 de taxa adicional em transferências acima de R$ 1.000,00</dd>
      </dl>
    </div>

    <div class="links d-flex justify-content-center flex-column mt-2">
      <%= link_to 'Voltar', root_path, class:'text-primary text-decoration-none fw-bolder' %>
    </div>
  </div>
</section>