config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  root 'home#index'
  resources :bank_accounts, only: :destroy do
    patch '/reactivate', to: 'bank_accounts#reactivate'
    get '/balance', to: 'bank_accounts#balance', on: :collection
    get '/statement', to: 'bank_accounts#statement', on: :collection
  end
  resources :deposits, only: %i[new create]
  resources :withdraws, only: %i[new create]
  resources :transfers, only: %i[new create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name surname birth_date email])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name surname birth_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_amount_field.html.erb
<div class="field form-floating">
  <%= f.number_field :amount, autofocus: true, autocomplete: 'amount', class: 'form-control mb-2', placeholder: ' ', step: 1 %>
  <%= f.label :amount %><br />
</div>

app/views/application/_client_registration_form.html.erb
<%= render 'devise/shared/error_messages', resource: resource %>
<div class="row g-2">
  <div class="field col-lg-6 form-floating">
    <%= f.text_field :registration_number, autofocus: true, autocomplete: 'registration_number', class: 'form-control', placeholder: ' ', readonly: f.object.persisted? %>
    <%= f.label :registration_number %><br />
  </div>

  <div class="field col-lg-6 form-floating">
    <%= f.date_field :birth_date, autocomplete: 'birth_date', class: 'form-control', placeholder: ' ' %>
    <%= f.label :birth_date %><br />
  </div>
</div>
<div class="row g-2">
  <div class="field col-lg-6 form-floating">
    <%= f.text_field :name, autocomplete: 'name', class: 'form-control', placeholder: ' ' %>
    <%= f.label :name %><br />
  </div>

  <div class="field col-lg-6 form-floating">
    <%= f.text_field :surname, autocomplete: 'surname', class: 'form-control', placeholder: ' ' %>
    <%= f.label :surname %><br />
  </div>
</div>
<div class="row g-2">
  <div class="field col-lg-12 form-floating">
    <%= f.email_field :email, autocomplete: 'email', class: 'form-control', placeholder: ' ', readonly: f.object.persisted? %>
    <%= f.label :email %><br />
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

</div>
<div class="row g-2 mb-2">
  <div class="field col-lg-6 form-floating">
    <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control', placeholder: ' ' %>
    <% if f.object.persisted? %>
      <i>(deixe em branco se não quiser alterar)</i>
      <br />
    <% end %>
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> caracteres no mínimo)</em>
    <% end %><br />
  </div>

  <div class="field col-lg-6 form-floating">
    <%= f.password_field :password_confirmation, autocomplete: 'new-password', class: 'form-control', placeholder: ' ' %>
    <%= f.label :password_confirmation %><br />
  </div>
</div>

app/views/application/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mb-2">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger mb-2">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:success] %>
  <div class="alert alert-success mb-2">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger mb-2">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/application/_homepage_options_bank_account_closed.html.erb
<div class="d-flex flex-row justify-content-between">
  <p>Olá <%= current_client.name %> | <%= current_client.bank_account_description %> </p>
  <%= button_to 'Sair', destroy_client_session_path, method: :delete, class: 'btn btn-outline-danger' %>
</div>
<div class="alert alert-danger">
  <h2 class="mb-4">Conta bancária encerrada</h2>
  <p>
    Sua conta bancária foi encerrada. Se você tiver encerrado sua conta, poderá reativá-la a qualquer momento. Basta clicar no botão abaixo.
  </p>
  <hr>
  <%= button_to 'Reativar conta bancária',
                bank_account_reactivate_path(current_client.bank_account),
                method: :patch,
                class: 'btn btn-outline-primary py-2' %>
</div>

app/views/application/_homepage_options_logged_in.html.erb
<div class="d-flex flex-row justify-content-between">
  <p>Olá <%= current_client.name %> | <%= current_client.bank_account_description %></p>
  <p><div id="minhaDiv" style="display:none" class="text-center fs-4"><%= number_to_currency(current_client.try(:bank_account).try(:real_balance)) %></p></div>
  <p><button type="button" onclick="Mudarestado('minhaDiv')"class= 'btn btn-outline-danger'>Mostrar/Ocultar Saldo</button></p>
  <%= button_to 'Sair', destroy_client_session_path, method: :delete, class: 'btn btn-outline-danger' %>
</div>
<p><h2 class="mb-4">Selecione uma opção</h2></p>
<p><div class="row g-2 mb-2"></p>
  <div class="col-lg-6">
    <%= link_to 'Depositar', new_deposit_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>

  <div class="col-lg-6">
    <%= link_to 'Sacar', new_withdraw_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>
</div>

<div class="row g-2 mb-2">
  <div class="col-lg-6">
    <%= link_to 'Transferir', new_transfer_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>

  <div class="col-lg-6">
    <%= link_to 'Saldo', balance_bank_accounts_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>
</div>

<div class="row g-2 mb-2">
  <div class="col-lg-6">
    <%= link_to 'Extrato', statement_bank_accounts_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>

  <div class="col-lg-6">
    <%= link_to 'Editar seus dados', edit_client_registration_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>
</div>
<div class="row g-2 mb-2">
  <div class="col-lg-6">
    <%= button_to 'Encerrar a minha conta',
                  bank_account_path(current_client.bank_account),
                  method: :delete,
                  onclick: "return confirmDestroy('Tem certeza que quer encerrar a sua conta bancária?')",
                  class: 'btn btn-outline-primary py-2 w-100' %>
  </div>
</div>

app/views/application/_homepage_options_logged_out.html.erb
<h2 class="mb-4">Escolha uma opção</h2>
<div class="row g-2">
  <p><br><div class="col-lg-6">
    <%= link_to 'Sou cliente', new_client_session_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div>

  <br><div class="col-lg-6">
    <%= link_to 'Abrir conta', new_client_registration_path, class: 'btn btn-outline-primary py-2 w-100' %>
  </div></p>
</div>